version: '3'
services:
    mongo:
        image: mongo:5.0
        restart: always
        container_name: wordle-helper-db-mongo
        hostname: host-mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        volumes:
          - ./docker-compose/data:/data/db
          - ./docker-compose/data/log:/var/log/mongodb/
        ports:
          - "27017:27017"
        networks:
            - wordle-network
    wordle-backend:
        build: ./../wordle-helper
        environment:
            MONGO_DB_URI: ${MONGODB_URI}
        ports:
            - "8080:8080"
        depends_on:
            - mongo
        networks:
            - wordle-network
    wordle-frontend:
        stdin_open: true
        command: npm start
        build: 
            context: ./../wordle-helper-front
            target: development
        ports:
            - "3000:3000"
        depends_on:
            - wordle-backend
        networks:
            - wordle-network
networks:
    wordle-network:
        driver: bridge