version: '3'
services:
    mongo:
        image: mongo:latest
        restart: always
        container_name: wordle-helper-db-mongo
        hostname: host-mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
          - ./data:/data/db
          - ./data/log:/var/log/mongodb/
        ports:
          - "27017:27017"
        networks:
            - wordle-network
    wordle-backend:
        build: ./../../wordle-helper
        ports:
            - "8080:8080"
        networks:
            - wordle-network
    wordle-frontend:
        stdin_open: true
        command: npm start
        build: ./../../wordle-helper-front
        ports:
            - "3000:3000"
        networks:
            - wordle-network
networks:
    wordle-network:
        driver: bridge