version: '3'
services:
    wordle-backend:
        build: ./../../wordle-helper
        ports:
            - "8080:8080"
        networks:
            - wordle-network
    wordle-frontend:
        stdin_open: true
        command: npm start
        build: ./../../wordle-helper-front
        ports:
            - "3000:3000"
        networks:
            - wordle-network
networks:
    wordle-network:
        driver: bridge